# This is an example configuration file that contains most useful parameter settings.
general:
  mode: verified-acc  # Compute verified accuracy.
  #enable_incomplete_verification: False
model:
  name: attitude
  input_ids: [0, 1, 2, 3, 4, 5]
  plt_ids: [[1, 4], [2], [3], [4], [5], [6]]
  path: "models/POLAR/AttitudeControl/CLF_controller_layer_num_3_new"
data:
  start: 0
  end: 100
  num_classes: 3
init:
  #min: [-0.45, -0.55, 0.65, -0.75, 0.85, -0.65]
  #max: [-0.44, -0.54, 0.66, -0.74, 0.86, -0.64]
  min: [-0.45, -0.55, 0.65, -0.75, 0.85, -0.65]
  max: [-0.45, -0.55, 0.65, -0.75, 0.85, -0.65]

#specification:
  #norm: .inf  # Linf norm (can also be 2 or 1).
  #epsilon: 100.  # epsilon=2./255.
solver:
  alpha-crown:
    iteration: 100   # Number of iterations for alpha-CROWN optimization. Alpha-CROWN is used to compute all intermediate layer bounds before branch and bound starts.
    lr_alpha: 0.1    # Learning rate for alpha in alpha-CROWN. The default (0.1) is typically ok.
  beta-crown:
    batch_size: 2048  # Number of subdomains to compute in parallel in beta-CROWN. Increase if you run out of memory.
    lr_alpha: 0.01  # Learning rate for optimizing the alpha parameters, the default (0.01) is typically ok, but you can try to tune this parameter to get better lower bound. 
    lr_beta: 0.05  # Learning rate for optimizing the beta parameters, the default (0.05) is typically ok, but you can try to tune this parameter to get better lower bound.
    iteration: 20  # Number of iterations for beta-CROWN optimization. 20 is often sufficient, 50 or 100 can also be used.
bab:
  #decision_thresh: 3
  timeout: 120  # Timeout threshold for branch and bound. Increase for verifying more points.
  branching:  # Parameters for branching heuristics.
    reduceop: min  # Reduction function for the branching heuristic scores, min or max. Using max can be better on some models.
    method: kfsb  # babsr is fast but less accurate; fsb is slow but most accurate; kfsb is usualy a balance.
    candidates: 3  # Number of candidates to consider in fsb and kfsb. More leads to slower but better branching. 3 is typically good enough.
