general:
  mode: runnerup
  enable_incomplete_verification: False
model:
  name: mnist_cnn_4layer
  path: models/sdp/mnist_cnn_a_adv.model
data:
  dataset: MNIST_SAMPLE
specification:
  epsilon: 0.3
attack:
  pgd_order: skip
solver:
  beta-crown:
    batch_size: 300
    iteration: 20
bab:
  timeout: 180
  decision_thresh: 99999999
  branching:
    reduceop: max
