general:
  mode: verified-acc
model:
  name: mnist_conv_big
  path: models/eran/mnist_conv_big_diffai.pth
data:
  dataset: MNIST_ERAN
specification:
  epsilon: 0.3
attack:
  pgd_restarts: 100
solver:
  beta-crown:
    batch_size: 1024
    iteration: 20
bab:
  timeout: 180
  branching:
    reduceop: max
