general:
  mode: verified-acc
  root_path: ../../vnncomp2021/benchmarks/eran  # Please update this path to point to the VNN-COMP 2021 repo
  csv_name: eran_instances.csv
  complete_verifier: bab-refine
data:
  dataset: MNIST
  start: 0
  end: 36
solver:
  beta-crown:
    batch_size: 500
    iteration: 20
  mip:
    parallel_solvers: 16
    refine_neuron_time_percentage: 0.8
