general:
  mode: verified-acc
  root_path: ../../vnncomp2021/benchmarks/marabou-cifar10  # Please update this path to point to the VNN-COMP 2021 repo
  csv_name: marabou-cifar10_instances.csv
data:
  dataset: CIFAR
  start: 0
  end: 71
bab:
  branching:
    candidates: 5
solver:
  beta-crown:
    iteration: 50
    lr_beta: 0.5
    batch_size: 1000
